### ISSUE TITLE
mvn package command fails

### ISSUE THREAD

**Issue by jandegithub** [opengeospatial/ets-ogcapi-edr10#136] opened 2024-10-18 14:39 UTC
**Describe the bug**
mvn package command fails to complete

**To Reproduce**
1. cd ets-ogcapi-edr10
2. mvn clean
3. mvn package
5. [ERROR] Failed to execute goal on project ets-ogcapi-edr10: Could not collect dependencies for project org.opengis.cite:ets-ogcapi-edr10:jar:1.2-SNAPSHOT
[ERROR] Failed to read artifact descriptor for org.opengis:geoapi-pending:jar:3.1-M04
[ERROR]         Caused by: The following artifacts could not be resolved: org.opengis:geoapi-pending:pom:3.1-M04 (present, but unavailable): Could not transfer artifact org.opengis:geoapi-pending:pom:3.1-M04 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [geotoolkit (http://maven.geotoolkit.org, default, releases+snapshots)]
[ERROR] Failed to read artifact descriptor for org.geotoolkit:geotk-referencing:jar:3.21
[ERROR]         Caused by: The following artifacts could not be resolved: org.geotoolkit:geotk-referencing:pom:3.21 (present, but unavailable): Could not transfer artifact org.geotoolkit:geotk-referencing:pom:3.21 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [geotoolkit (http://maven.geotoolkit.org, default, releases+snapshots)]

**Expected behavior**
Expect it to download the relevant modules

**Screenshots**

**Additional context**
CentOS Linux release 7.7.1908 

java version "17.0.11" 2024-04-16 LTS
Java(TM) SE Runtime Environment (build 17.0.11+7-LTS-207)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.11+7-LTS-207, mixed mode, sharing)
/usr/lib/jvm/jdk-17-oracle-x64/bin/java

Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: /usr/lib/jvm/apache-maven-3.9.9
Java version: 17.0.11, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-17-oracle-x64
Default locale: en_US, platform encoding: UTF-8

**Comment by dstenger** [comment] 2024-10-18 14:51
Thank you for reporting.

The problem is connected to the Maven version and occurs in all test suites.
Please review the response in https://github.com/opengeospatial/ets-wfs20/issues/249#issuecomment-1357431309 which describes how to solve the problem.

Can you please close this issue if you do not have any further questions?

**Closed as completed** 2024-10-21 09:28 UTC
Labels: question
